language: go
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip
env:
  - GO111MODULE=on
cache:
  directories:
    - $GOPATH/pkg/mod
dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
  - redis-server
  - mysql
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - mysql -e 'CREATE DATABASE gobay DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - wget https://mirrors.tuna.tsinghua.edu.cn/apache/kafka/2.5.0/kafka_2.13-2.5.0.tgz -O /tmp/kafka_2.13-2.5.0.tgz
  - tar zxvf /tmp/kafka_2.13-2.5.0.tgz -C /tmp/
  - /tmp/kafka_2.13-2.5.0/bin/zookeeper-server-start.sh -daemon /tmp/kafka_2.13-2.5.0/config/zookeeper.properties
  - /tmp/kafka_2.13-2.5.0/bin/kafka-server-start.sh -daemon /tmp/kafka_2.13-2.5.0/config/server.properties
script:
  - golangci-lint run --timeout=3m --skip-dirs=testdata --tests=false
  - go test -v -count=1 ./...
